---
name: Testing

on:
  workflow_dispatch:
    inputs:
      command:
        description: make command to run
        required: true
        default: generate

jobs:
  generate:
    runs-on: ubuntu-latest
    container: ubuntu:18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          persist-credentials: false
          fetch-depth: 0

      #      - name: Setup git
      #        run: |
      #          set -x
      #          apt update
      #          apt-get install -y git
      #          git config --local user.email "deemes79@googlemail.com"
      #          git config --local user.name "udondan"

      #      - name: inject a change
      #        run: echo "hello world" > testfile

      - name: Check for changes
        id: changes
        uses: actions/checkout@v1
        continue-on-error: true
        run: |
          set -x +e
          git diff --quiet
          echo ::set-output name=CHANGED::$?

      - name: TESTING
        run: echo ${{ steps.changes.outputs.CHANGED }}

      - name: Do something if CHANGED
        run: echo CHANGE DETECTED
        if: steps.changes.outputs.CHANGED == '1'
